# 1- Fondamentaux du Python

## a) Dictionnaires et tuples

### Créez un tuple qui associe votre login à votre âge

In [6]:
mine = ('fleste-l', 54)
mine

('fleste-l', 54)

### Initialisez un dictionnaire à deux entrées qui associe le login de chacun de vos voisins à leur âge

In [7]:
voisins = {"pierre": 41, "fred": 47}
voisins

{'fred': 47, 'pierre': 41}

### Récupérez l'âge de l'un d'entre eux à partir du dictionnaire

In [8]:
voisins['fred']

47

### Ajoutez une entrée avec votre propre login

In [9]:
voisins['fleste-l'] = 54
voisins

{'fleste-l': 54, 'fred': 47, 'pierre': 41}

## b) Manipulation de listes

### Créez une liste A contenant les entiers suivants: 1, 3, 2, 7, 4, 10, 46

In [10]:
A = [1,3,2,7,4,10,46]
A

[1, 3, 2, 7, 4, 10, 46]


### Affichez les 3 premiers éléments de la liste A - en une ligne de code

In [11]:
A[0:3]

[1, 3, 2]

### Créez une liste B qui contient seulement les 3e, 4e et 5e éléments de A . Votre ligne de code ne devrait contenir que 8 caractères (sans compter les espaces) - Vérifiez bien votre résultat!

In [12]:
B = A[2:5]
B

[2, 7, 4]

### Concaténez les listes A et B pour former la liste C

In [13]:
C = A + B
C

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4]

### Ajoutez le nombre 5 à la liste A

In [14]:
A.append(5)
A

[1, 3, 2, 7, 4, 10, 46, 5]

### Ajoutez un élément nul à la liste C

In [15]:
C.append(None)
C

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4, None]

## b) Fonctions

In [16]:
def f(lst, n=2):
    lst *= n
    return(lst)
f([7,8,9])

[7, 8, 9, 7, 8, 9]

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

In [17]:
def f(lst, n):
    lst *= n
    return(lst)
f([4,5,6], 3)

[4, 5, 6, 4, 5, 6, 4, 5, 6]

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [18]:
def f(lst, n=2):
    lst *= n
    return(lst)
f([7,8,9])

[7, 8, 9, 7, 8, 9]

## c) Boucles

### Avec une boucle 'while', imprimez chaque élément de la liste C jusqu'à l'élément nul

In [19]:
i = 0
while i < 11:
    print(C[i])
    i+=1

1
3
2
7
4
10
46
2
7
4
None


### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [20]:
i = 0
for val in A:
    if val % 2 == 0:
        i+=1
print("A contient", i, "nombres entiers pairs")

A contient 4 nombres entiers pairs


### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [21]:
C = [element for element in A if element %2 == 0]

In [22]:
for val in A:
    if val % 2 == 0:
        C.append(val)
C

[2, 4, 10, 46, 2, 4, 10, 46]

# 2- Opérations sur matrices avec numpy

### Transformer les listes A et B en tableaux numpy a et b

In [23]:
import numpy as np
a = np.array(A)
b = np.array(B)
a, b

(array([ 1,  3,  2,  7,  4, 10, 46,  5]), array([2, 7, 4]))

### Concaténez-les pour former un tableau c (a, b --> c)

In [24]:
c = np.append(a, b)
c

array([ 1,  3,  2,  7,  4, 10, 46,  5,  2,  7,  4])

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [25]:
c / 3

array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  1.66666667,  0.66666667,  2.33333333,
        1.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [26]:
np.sum(c)

91

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [27]:
M = np.random.randint(10, size=(4,4))
N = np.random.randint(10, size=(4,4))

In [28]:
M

array([[3, 2, 8, 4],
       [1, 1, 7, 2],
       [2, 4, 5, 5],
       [0, 2, 5, 1]])

In [29]:
N

array([[3, 9, 7, 1],
       [3, 3, 7, 8],
       [1, 5, 9, 4],
       [9, 9, 9, 1]])

### Aditionnez les deux matrices

In [30]:
M + N

array([[ 6, 11, 15,  5],
       [ 4,  4, 14, 10],
       [ 3,  9, 14,  9],
       [ 9, 11, 14,  2]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [31]:
%%time
np.dot(M,N)

CPU times: user 25 µs, sys: 16 µs, total: 41 µs
Wall time: 38.9 µs


array([[ 59, 109, 143,  55],
       [ 31,  65,  95,  39],
       [ 68, 100, 132,  59],
       [ 20,  40,  68,  37]])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 

In [32]:

R = np.zeros((4,4))
for i in range(len(M)):
    for j in range(len(N[0])):
        for k in range(len(N)):
            R[i][j] += M[i][k] * N[k][j]
for r in R:
    print(r)

[ 59. 109. 143.  55.]
[31. 65. 95. 39.]
[ 68. 100. 132.  59.]
[20. 40. 68. 37.]


### ** Comparez son temps de calcul à la fonction de numpy avec de très grosses matrices en entrée

In [33]:
R = (4,4)
R = np.zeros(R)
R

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
import numpy
help(numpy.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
  