# 0- Bases de jupyter

Exécuter une cellule: `ctrl + entrée`  
Exécuter une cellule et passer à la suivante: `shift + entrée`  
Créer une cellule au dessus: `esc + a`  
Créer une cellule en dessous: `esc + b`  
Supprimer une cellule: `esc + dd`  

Boucle infinie: interrompez le kernel (bouton stop) ou redémarrez-le carrément 


# 1- Fondamentaux du Python

## b) Manipulation de listes

In [13]:
A = [1,3,2,7,4,10,46]
B = A[2:5]

### Concaténez les listes A et B pour former la liste C

In [14]:
# Avec l'opérateur
C = A + B

In [15]:
C

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4]

In [16]:
A

[1, 3, 2, 7, 4, 10, 46]

In [17]:
# Avec la méthode extend()
A.extend(B)

In [18]:
A

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4]

### Ajoutez le nombre 5 à la liste A

In [19]:
# Avec l'opérateur +
A += [5]

In [20]:
A

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4, 5]

In [21]:
# Avec la méthode append()
A.append(5)

In [22]:
A

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4, 5, 5]

## b) Fonctions

### Écrivez une fonction qui prend comme arguments une liste 'lst' et un entier 'n' et retourne le résultat de n concaténations de 'lst' avec elle-même (ex: lst=[1,2,3], n=2 --> [1,2,3,1,2,3])

### Vous voulez rendre le paramètre 'n' optionnel et fixer sa valeur à 2 par défaut. Comment faites-vous?

In [26]:
def n_concat(lst, n=2):
    return lst * n

In [27]:
n_concat([1,2,3])

[1, 2, 3, 1, 2, 3]

In [28]:
n_concat([1,2,3], 4)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

## c) Boucles

### Calculez, avec une boucle 'for', le nombre d'entiers pairs présents dans la liste A

In [31]:
A

[1, 3, 2, 7, 4, 10, 46, 2, 7, 4, 5, 5]

In [30]:
count = 0
for number in A:
    if number % 2 == 0:
        count += 1
count

6

### Réécrivez l'expression suivante avec une boucle 'for' sur plusieurs lignes

In [ ]:
C = [element for element in A if element %2 == 0]

In [32]:
C = []
for element in A:
    if element % 2 == 0:
        C.append(element)
C

[2, 4, 10, 46, 2, 4]

# 2- Opérations sur matrices avec numpy

In [34]:
import numpy as np
a = np.array(A)
b = np.array(B)
c = np.concatenate((A, B))

### Divisez tous les éléments de c par 3 (sans utiliser de boucle)

In [35]:
c / 3

array([ 0.33333333,  1.        ,  0.66666667,  2.33333333,  1.33333333,
        3.33333333, 15.33333333,  0.66666667,  2.33333333,  1.33333333,
        1.66666667,  1.66666667,  0.66666667,  2.33333333,  1.33333333])

### Calculez la somme de tous les éléments de c (sans utiliser de boucle)

In [40]:
sum(c)

109

In [41]:
np.sum(c)

109

### Exécutez les trois cellules suivantes pour visualiser les matrices M et N

In [42]:
M = np.random.randint(10, size=(4,4))
N = np.random.randint(10, size=(4,4))

In [44]:
M

array([[0, 0, 2, 3],
       [0, 4, 1, 7],
       [7, 4, 2, 0],
       [9, 3, 2, 8]])

In [45]:
N

array([[3, 6, 7, 0],
       [8, 2, 1, 6],
       [0, 3, 4, 2],
       [6, 8, 3, 0]])

### Calculez le produit matriciel de M et N. Vérifiez votre opération en calculant les premières cellules à la main

In [43]:
# Noooooooonnnn
M * N

array([[ 0,  0, 14,  0],
       [ 0,  8,  1, 42],
       [ 0, 12,  8,  0],
       [54, 24,  6,  0]])

In [49]:
np.matmul(M, N)

array([[ 18,  30,  17,   4],
       [ 74,  67,  29,  26],
       [ 53,  56,  61,  28],
       [ 99, 130,  98,  22]])

In [46]:
M @ N

array([[ 18,  30,  17,   4],
       [ 74,  67,  29,  26],
       [ 53,  56,  61,  28],
       [ 99, 130,  98,  22]])

In [48]:
np.dot(M,N)

array([[ 18,  30,  17,   4],
       [ 74,  67,  29,  26],
       [ 53,  56,  61,  28],
       [ 99, 130,  98,  22]])

ATTENTION!! Le comportement de ces fonctions peut différer si les arrays n'ont pas 2 dimensions. Bien lire la doc et tester avant d'utiliser!

## NOTE: Pour accéder à des valeurs dans la matrice

In [51]:
M[0][1]

0

In [52]:
M[0,1]

0

In [53]:
M[0,:]

array([0, 0, 2, 3])

In [58]:
M[:,0]

array([0, 0, 7, 9])

In [59]:
M[:3, 0]

array([0, 0, 7])

In [62]:
M[:3, 1:3]

array([[0, 2],
       [4, 1],
       [4, 2]])

In [64]:
M[:,0:4:2]

array([[0, 2],
       [0, 1],
       [7, 2],
       [9, 2]])

### ** Bonus: Écrivez vous-mêmes une fonction de produit matriciel, avec des boucles imbriquées 

In [68]:
def produit_matriciel (M, N):
    a, b = M.shape
    c, d = N.shape
    result = np.zeros((a,d), dtype="int")
    
    if b != c:
        raise Exception("Dimensions of input matrices don't allow multiplication")
    for i in range(a):
        for j in range(d):
            cell = 0
            for k in range(b):
                cell += M[i][k] * N[k][j]
            result[i][j] = cell
    return result

In [69]:
produit_matriciel(M,N)

array([[ 18,  30,  17,   4],
       [ 74,  67,  29,  26],
       [ 53,  56,  61,  28],
       [ 99, 130,  98,  22]])

### ** Comparez son temps de calcul à la fonction de numpy avec de très grosses matrices en entrée

In [71]:
M = np.random.randint(10, size=(2000,2000))
N = np.random.randint(10, size=(2000,2000))

In [72]:
%time M @ N
%time produit_matriciel(M,N)

CPU times: user 5.97 s, sys: 23.4 ms, total: 6 s
Wall time: 6.02 s


KeyboardInterrupt: 